### ISSUE TITLE
localStorage - token's time limit problem

### ISSUE THREAD

**Issue by bariskbayram** [bariskbayram/getchapull-vuejs-frontend#1]
When you log in to web app and close the tab without logout, sometimes it causes a problem. I am storing token and isLoggedIn informations in localStorage, so when the token is expired, localStorage still storage the isLoggedIn that is "True". In this case, if you try to go to web app, it says "404 page not found". This error page is designed by me and it happens when you try to see someone's profile without authentication, so it is 403 Error act. 

When the token is expired, localStorage must be cleared or something else.

Use devtools to clear storage manually to solve it by hand.

**Comment by Ginkodan** [comment]
One way would be to check if the token has expired, if so delete it from the localStorage. 
You will need to add a expirationDate first on the Backend so you can add something like this:

```
const expirationDate = localStorage.getItem('expirationDate')
            const now = new Date()
            if (now >= expirationDate) {
               // clear localstore
              return
            } 


```

**Comment by bariskbayram** [comment]
I will try to do as you say, thanks a lot

> One way would be to check if the token has expired, if so delete it from the localStorage.
> You will need to add a expirationDate first on the Backend so you can add something like this:
> 
> ```
> const expirationDate = localStorage.getItem('expirationDate')
>             const now = new Date()
>             if (now >= expirationDate) {
>                // clear localstore
>               return
>             } 
> ```

I will try to do as you say, thanks a lot
